name = "twilight-haze-d33b"
main = "worker.js"
compatibility_date = "2025-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "dialects-database"
database_id = "3bf61bb9-0d72-4041-a97a-c4179b28d7b8"

[vars]
OPENAI_API_KEY = "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
"
